theme: jekyll-theme-slate
title: Trail Blazer
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
docs:
  - title: Getting Started
    children:
      - title: "Quick-Start Guide"
        url: /docs/index.md
      - title: "Structure"
        url: /docs/run.md
